name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test 1a
      id: test-1a
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test 1a
        setup-command: npm install
        command: npm run test tests/exercice_1a.test.js
        timeout: 10
        max-score: 1
    - name: test 1b
      id: test-1b
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test 1b
        setup-command: npm install
        command: npm run test tests/exercice_1b.test.js
        timeout: 10
        max-score: 1
    - name: test 1c
      id: test-1c
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test 1c
        setup-command: npm install
        command: npm run test tests/exercice_1c.test.js
        timeout: 10
        max-score: 1
    - name: test 2a
      id: test-2a
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test 2a
        setup-command: npm install
        command: 'npm run test tests/exercice_2a.test.js '
        timeout: 10
        max-score: 1
    - name: test 2b
      id: test-2b
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test 2b
        setup-command: npm install
        command: 'npm run test tests/exercice_2b.test.js '
        timeout: 10
        max-score: 1
    - name: test 2c
      id: test-2c
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test 2c
        setup-command: npm install
        command: 'npm run test tests/exercice_2c.test.js '
        timeout: 10
        max-score: 1
    - name: test 3
      id: test-3
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test 3
        setup-command: npm install
        command: npm run test tests/exercice_3.test.js
        timeout: 10
        max-score: 1
    - name: test 4
      id: test-4
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test 4
        setup-command: npm install
        command: npm run test tests/exercice_4.test.js
        timeout: 10
        max-score: 1
    - name: test 5
      id: test-5
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test 5
        setup-command: npm install
        command: npm run test tests/exercice_5.test.js
        timeout: 10
        max-score: 1
    - name: test 6
      id: test-6
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test 6
        setup-command: npm install
        command: npm run test tests/exercice_6.test.js
        timeout: 10
        max-score: 1
    - name: test 7
      id: test-7
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test 7
        setup-command: npm install
        command: npm run test tests/exercice_7.test.js
        timeout: 10
        max-score: 1
    - name: test 8
      id: test-8
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test 8
        setup-command: npm install
        command: npm run test tests/exercice_8.test.js
        timeout: 10
        max-score: 1
    - name: test 9
      id: test-9
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: test 9
        setup-command: npm install
        command: npm run test tests/exercice_9.test.js
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-1A_RESULTS: "${{steps.test-1a.outputs.result}}"
        TEST-1B_RESULTS: "${{steps.test-1b.outputs.result}}"
        TEST-1C_RESULTS: "${{steps.test-1c.outputs.result}}"
        TEST-2A_RESULTS: "${{steps.test-2a.outputs.result}}"
        TEST-2B_RESULTS: "${{steps.test-2b.outputs.result}}"
        TEST-2C_RESULTS: "${{steps.test-2c.outputs.result}}"
        TEST-3_RESULTS: "${{steps.test-3.outputs.result}}"
        TEST-4_RESULTS: "${{steps.test-4.outputs.result}}"
        TEST-5_RESULTS: "${{steps.test-5.outputs.result}}"
        TEST-6_RESULTS: "${{steps.test-6.outputs.result}}"
        TEST-7_RESULTS: "${{steps.test-7.outputs.result}}"
        TEST-8_RESULTS: "${{steps.test-8.outputs.result}}"
        TEST-9_RESULTS: "${{steps.test-9.outputs.result}}"
      with:
        runners: test-1a,test-1b,test-1c,test-2a,test-2b,test-2c,test-3,test-4,test-5,test-6,test-7,test-8,test-9